### PR TITLE
ci: Add vnu to dev docker image

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Comment by larseggert** [comment]
Whoops - why is the diff so huge?

**Comment by rjsparks** [comment]
This currently assumes an x86 architecture on the developer's machine.

**Comment by larseggert** [comment]
Oh. Yes. The alternate way to do this is to install the JDK from `apt` and then just pull the JAR. Will do that.

**Comment by NGPixel** [comment]
> Whoops - why is the diff so huge?

The original file was incorrectly created using CRLF instead of just LF (thanks Windows). So this is ok.

**Review by NGPixel — APPROVED** [review]

**Pull request merged**
