### PR TITLE
feat: Upgrade bootstrap to 5.3.0 and enable dark mode

### LINKED ISSUE #3365: Datatracker dark mode
`type_enhancement`   |    by csp@csperkins.org

___

Hi,

Too many IETF meetings in the middle of the night for me, perhaps, but if it were possible for the datatracker to have an automatic dark mode style sheet, based on system settings, that would be wonderful. :) 

And yes, low priority, clearly. 

Cheers,
Colin

___
_Issue migrated from trac:3365 at 2022-03-04 09:09:44 +0000_

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #3365

### CODE REVIEW

**Comment by NGPixel** [comment]
The bootstrap dependency is current set on alpha3. I think the final 5.3 is now available.

**Comment by rjsparks** [comment]
I want to hold merging this until feat/django4 is in main and is deployed (to better help with diagnosing deployment issues)

**Comment by NGPixel** [comment]
Some issues I noticed:

- The IETF logo on the homepage should vary to light text when in dark mode.
- The agenda page isn't adapted for dark mode (I'll contribute to this PR to add the missing bits)
- Might be best to add a button in the header or footer to quickly switch between light and dark mode. Not everyone will know to look in Preferences. When first loading the site, not logged in, it was automatically set to "Dark" instead of "Auto"?

**Comment by rjsparks** [comment]
We should probably make at darkmode branch for this to land in and get some dev instance feedback from

**Comment by larseggert** [comment]
>     * The IETF logo on the homepage should vary to light text when in dark mode.

I made that change (also to other logos).

>     * The agenda page isn't adapted for dark mode (I'll contribute to this PR to add the missing bits)

Thanks!

>     * Might be best to add a button in the header or footer to quickly switch between light and dark mode. Not everyone will know to look in Preferences.

Maybe. It'd make it pretty busy.

> When first loading the site, not logged in, it was automatically set to "Dark" instead of "Auto"?

Odd. Do you maybe have previous data in localstorage? I just tried in private browsing mode and it comes up in "auto".

**Pull request merged**
