### PR TITLE
docs: Suggest cloning a fork [ci skip]

### PR DESCRIPTION
**Pull request by jimfenton**
Ready to be merged.

### CODE REVIEW

**Review by rjsparks — APPROVED** [review]

**Comment by rjsparks** [comment]
Hi Jim - we don't need the "ready for merge" convention anymore - PRs signal that by themselves.
Note that we want Conventional Commit formatted commit messages, not just PR titles.

**Comment by jimfenton** [comment]
Got it: As you can see from my title edits, there was a little trial and error on this one. The semantic pull request checker says it's happy if one of the commits or the title of the pull request follow the guidelines, but apparently that is configured differently here. Maybe the CONTRIBUTING guide should be a little more specific on that; right now it just says "Consider starting the commit message..."

**Comment by NGPixel** [comment]
@jimfenton I updated the guide with clearer instructions and examples:

https://github.com/ietf-tools/.github/blob/main/CONTRIBUTING.md#git-commit-messages

**Comment by jimfenton** [comment]
That makes it clearer for me; thanks.

Also, it may be due to my GitHub security configuration (2FA, SSH keys) or the fact that I'm using Sourcetree, but I wasn't able to push to my forked repo when I used https://github.com/jimfenton/datatracker.git . I had to adjust my URL to git@github.com:jimfenton/datatracker.git to get it to work. I don't know how general this problem is though, so I don't know how it should be represented in the README.

**Comment by NGPixel** [comment]
This is normal, as `https://github.com/jimfenton/datatracker.git` is an HTTPS/Basic authentication format URI. When using SSH keys, you must use the `git@github.com](mailto:git@github.com):jimfenton/datatracker.git` format.

When clicking the <kbd>Code</kbd> button on a repo, you're presented with both the HTTPS and SSH options, each with their proper URI.

**Pull request merged**
