### PR TITLE
build: Install fonts from xml2rfc-fonts

### LINKED ISSUE #6294: Install fonts from xml2rfc-fonts repository
### Description

In order to generate internet draft PDFs with correct fonts, use fonts from [xml2rfc-fonts](https://github.com/ietf-tools/xml2rfc-fonts) font repository.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kesara**
Fixes #6294

### CODE REVIEW

**Review by rjsparks — APPROVED** [review]

**Comment by rjsparks** [comment]
@kesara @jennifer-richards : checking as seems to have fallen into the meeting cracks - is this still the right thing to do, or did it get superseded with changing the dependency to `xml2rfc[pdf]>=3.23.0`?

**Comment by kesara** [comment]
> @kesara @jennifer-richards : checking as seems to have fallen into the meeting cracks - is this still the right thing to do, or did it get superseded with changing the dependency to `xml2rfc[pdf]>=3.23.0`?

This PR is still valid. `xml2rfc[pdf]` extra does not install fonts.

**Comment by jennifer-richards** [comment]
This updates the dockerfile used to create the `app` container in a dev environment, but won't affect the containers we deploy to production. That's set up in `dev/build`. I think the intention is to get these fonts to production?

**Comment by kesara** [comment]
> This updates the dockerfile used to create the `app` container in a dev environment, but won't affect the containers we deploy to production. That's set up in `dev/build`. I think the intention is to get these fonts to production?

So the correct Dockerfile to use is `docker/base.Dockerfile`?

**Review by rjsparks — CHANGES_REQUESTED** [review]
Requesting changes before merging to touch the files that would affect production

**Comment by kesara** [comment]
I have made requested changes with https://github.com/ietf-tools/datatracker/pull/6300/commits/09bb24e3eb81ea7d16e7f91890f72867fbf57757

**Review by NGPixel — APPROVED** [review]

**Review by rjsparks — APPROVED** [review]

**Pull request merged**
