### PR TITLE
Change button style

### PR DESCRIPTION
**Pull request by vanillajonathan**
Not all buttons can be primary. Change to secondary, and since there is many of them, use the outline variant.

### CODE REVIEW

**Review by lunaroco33 — COMMENTED** [review]
srdrtfkjj bñhlihop lkljoiphpiig  mm.hilhñhoblk

**Comment by rjsparks** [comment]
This doesn't look complete (the focus on the community app is odd), and should be supported by an issue that outlines the concern it's really trying to address that we can discuss. Closing this PR rather than suggesting changes at this point..

**Comment by vanillajonathan** [comment]
My concern is that in UI/UX design you expect there to be one primary button, not many. Hence I propose to change `btn-primary` to `btn-secondary`. Since none of them really are primary. Since there are many, I propose using the outline variant `btn-outline-secondary` which is less prominent.

**Comment by rjsparks** [comment]
Understood. We have a professional UI/UX review in the long term plan and this will be addressed application-wide with that.

**Pull request closed without merging**
