### PR TITLE
Search UI

### PR DESCRIPTION
**Pull request by kivinen**
Implements #4711 i.e., allows using control-click or context menu to open items in the top right search list to open multiple documents in different tabs.

### CODE REVIEW

**Comment by larseggert** [comment]
There are some meeting-related changes in this PR that seem unrelated?

**Comment by kivinen** [comment]
Lars Eggert writes:
> There are some meeting-related changes in this PR that seem unrelated?

Most likely they are from my previous change
https://github.com/ietf-tools/datatracker/pull/4701 that was already
merged in. I did create new branch for these changes, but guess I
should have done something else also to get rid of those changes.
-- 
***@***.***

**Comment by larseggert** [comment]
You need to create your new branch off tzaware, not of another branch that has changes.

**Comment by rjsparks** [comment]
At this point, it would be better to recreate this PR from current main.
I took a look at detangling this myself, and I could do so in a pinch, but I think it will be easier for Tero when he has a moment.

**Comment by kivinen** [comment]
Robert Sparks writes:
> At this point, it would be better to recreate this PR from current main.
> I took a look at detangling this myself, and I could do so in a pinch, but I
> think it will be easier for Tero when he has a moment.

If you tell me how to do that I can do it, but every time I try to do
something with git/github it takes about 2 hours, and couple of
times, when I rm -rf everything and start over... 
-- 
***@***.***

**Comment by rjsparks** [comment]
This is moved to #4747.

**Comment by rjsparks** [comment]
(I tried to do a soft-reset juggle, but ended up with exactly the opposite of what I wanted. I built the correct thing on a fresh checkout of main instead.)

**Pull request closed without merging**
