### PR TITLE
feat: Make the "report a bug" links more visible

### PR DESCRIPTION
**Pull request by larseggert**
Also rework the page footer somewhat, while we're here.

### CODE REVIEW

**Comment by rjsparks** [comment]
I'm not sure this is enough.
(I can live with the suggested footer rework).
I think we may need (for awhile) to put report-a-bug in the menus somewhere, or at least on the menu bar

**Comment by larseggert** [comment]
It's in the "other" menu

**Comment by rjsparks** [comment]
and yet we _still_ have chairs asking "how do I report a bug?" regularly.

I'm thinking of something more like:

image

unless you think that's just too obnoxious.

**Comment by rjsparks** [comment]
If we go that route, we could place it only for logged in users to start with

**Review by rjsparks — APPROVED** [review]

**Pull request merged**
