### PR TITLE
fix: Use email or name when building community list view

### LINKED ISSUE #7036: Personal community list view crashes if email addresses are all inactive
### Describe the issue

If all email addresses for a logged-in user are deactivated (`active=False`), the `ietf.community.views.view_list()` view causes a 500 error if they view their own list.

This is because the view tries to look up the `manage_list` view with `clist.person.email_address`, which does not return an address in this case.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by microamp**
Fixes #7036 

An additional argument has been added to pass the `email_or_name` variable through.

### CODE REVIEW

**Comment by rjsparks** [comment]
Since this is fixing a crash bug, we should add, or modify an existing test to include, a test that exercises the condition that led to the crash.

That test should also cover the view for person Y after having constructed a person X with name N and email E, and a person Y with name N (note same name) but no email.

**Review by rjsparks — CHANGES_REQUESTED** [review]
See the earlier note re: tests

**Review by jennifer-richards — COMMENTED** [review]
Looks good to me, agree that it should have a test.

**Comment by jennifer-richards** [comment]
I added a test - which fails because it turns out this goes deeper. There's a similar issue in `list_menu.html` with the added wrinkle that it's included both in the view we're already touching and in `group_documents.html`.

**Comment by microamp** [comment]
> I added a test - which fails because it turns out this goes deeper. There's a similar issue in `list_menu.html` with the added wrinkle that it's included both in the view we're already touching and in `group_documents.html`.

Thanks for having a go at it! (It was on my list at the code sprint, but I ran out of time.)

I'll have a look at the files you mentioned when I can.

**Comment by rjsparks** [comment]
@jennifer-richards @microamp Is this still something to pursue?

**Review by jennifer-richards — APPROVED** [review]
lgtm

In my previous comments I was worried because the `email_or_name` variable is not set when the `list_menu.html` is included via `group_documents.html` in the `group_documents()` view. On closer review, there are guards in place so the `email_or_name` is not needed in the group context.

**Review by rjsparks — APPROVED** [review]

**Pull request merged**
