### PR TITLE
feat: allow openId to choose an unactive email if there are none active

### PR DESCRIPTION
**Pull request by rjsparks**

### CODE REVIEW

**Comment by rjsparks** [comment]
cc: @rpcross @jennifer-richards

**Comment by jennifer-richards** [comment]
I am not familiar with what is done with the openid claims, but is it a problem to be handing back an email address that someone inactivated? If the other end of the exchange can be changed to handle the empty claim I'd think that's preferable to propagating an address that was deactivated. If not, maybe better to transmit a canned and identifiable "not-an-address"?

Also, why "unactive" rather than "inactive"?

**Comment by rpcross** [comment]
We currently use claims.email from Datatracker as the email address and unique (DT related) identifier of the registration, used when calling DT APIs. An empty or generic string would break this.

**Review by jennifer-richards — APPROVED** [review]
Assuming you'll change the "u" to "i" in the names and approving.

**Pull request merged**
