### PR TITLE
feat: add target to bibxml-ids

### PR DESCRIPTION
**Pull request by rjsparks**

### CODE REVIEW

**Comment by rjsparks** [comment]
cc: @cabo

**Review by ajeanmahoney — APPROVED** [review]

**Comment by cabo** [comment]
> cc: @cabo

LGTM (but then I don't understand all the context).

**Review by jennifer-richards — APPROVED** [review]

**Review by gabor38 — COMMENTED** [review]
illegal

**Review by gabor38 — COMMENTED** [review]
illegal.

**Pull request merged**
