### PR TITLE
feat: show active adhoc groups on group menu. Fixes #4339.

### LINKED ISSUE #4339: `hotrfc` not accessible from "Groups" menu
### Describe the issue

https://datatracker.ietf.org/group/hotrfc/about/ exists, but I can't figure out how to get to it from within the menu structure.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rjsparks**
This is *gross*.

Please pull the PR and look at the result. I don't think it's what we really want.

### CODE REVIEW

**Comment by rjsparks** [comment]
image

**Comment by rjsparks** [comment]
Fixes #4339

**Comment by larseggert** [comment]
Why is the stuff in the screenshot gross? I think this is better than not showing these at all.

**Comment by larseggert** [comment]
Would a better approach to be to give these groups different shapes/homes, e.g., directorates, teams, etc.?

**Comment by larseggert** [comment]
All of these could become teams under GEN, IMO, and we could eliminate the concept of an "ad hoc group".

**Comment by rjsparks** [comment]
Making them genarea teams would address my discomfort completely - would, e.g, the IEPG organizers have any issue with that?

**Comment by larseggert** [comment]
It was proposed that they could be under OPS, which IMO makes sense.

**Comment by rjsparks** [comment]
I've done this to the sandbox (effects will only last until it resets its database tomorrow).
If we go down this path, I will need to make it so that teams have full meeting materials support (which should just be groupfeatures configuration). Where/if these things appear in the group filters on the meeting agenda page will also change.

**Comment by rjsparks** [comment]
Changes made to the production database - closing this as OBE

**Pull request closed without merging**
