### PR TITLE
fix: remove order from DocumentInfo as apparently unneeded (fixes #5245)

### LINKED ISSUE #5245: Verify whether DocumentInfo.order is ever used
If it is not used, remove it.

### PR DESCRIPTION
**Pull request by Spectre17**
Fixes #5245. Includes migration, however I did not test the reverse.

### CODE REVIEW

**Comment by rjsparks** [comment]
Holding for after deploy of feat/postgres (as it contains migrations)

**Review by jennifer-richards — DISMISSED** [review]
Looks good, just needs its migration to be updated (renumbered, update the dependency name/number).

**Comment by jennifer-richards** [comment]
Yuck, I seem to have botched my attempt to helpfully update this.

**Comment by jennifer-richards** [comment]
Ok, that's cleaned up. Sorry for the distraction!

**Review by rjsparks — APPROVED** [review]

**Pull request merged**
