### PR TITLE
ci: Switch to using geckodriver

### PR DESCRIPTION
**Pull request by larseggert**
Because that works also on `amd64`.

### CODE REVIEW

**Review by jennifer-richards — DISMISSED** [review]
Looks ok to me (and tests run, though with a couple failures, on my m2 mac)

**Review by jennifer-richards — COMMENTED** [review]
Withdrew my approval - noticed that the geckodriver tests didn't actually run here. I think it pulls the standard base image, so doesn't have geckodriver installed. Testing locally, there are some changes needed.

**Comment by jennifer-richards** [comment]
Those commits fix the selenium tests under `ietf.meeting.tests_js` for me (apologies for the `sleep()` in the second one, but I haven't found a better way)

**Comment by jennifer-richards** [comment]
Still a failure in `ietf.doc.tests_js.EditAuthorsTests.test_add_author_forms`

**Review by rjsparks — CHANGES_REQUESTED** [review]
Please move this to draft until it passes in both CI and on both mac and windows developer's platforms

**Comment by larseggert** [comment]
You need to rebuild the base docker image locally first to have  geckodriver available in the dev image.

**Comment by jennifer-richards** [comment]
> You need to rebuild the base docker image locally first to have geckodriver available in the dev image.

That's what I've done locally (mac). Can you check whether the tests I touched work on your system? (I'm a little worried that I may have undone workarounds that are platform dependent in my purported fixes)

**Comment by larseggert** [comment]
@jennifer-richards I see these three failures still:
```
======================================================================
FAIL: test_upcoming_view_filter_hide_area (ietf.meeting.tests_js.InterimTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/ietf/meeting/tests_js.py", line 1169, in test_upcoming_view_filter_hide_area
    self.do_upcoming_view_filter_test('?show=mars&hide=%s' % area.acronym)
  File "/workspace/ietf/meeting/tests_js.py", line 1048, in do_upcoming_view_filter_test
    self.assert_upcoming_meeting_visibility(visible_meetings)
  File "/workspace/ietf/meeting/tests_js.py", line 1003, in assert_upcoming_meeting_visibility
    self.assertEqual(unexpected, set(), "Unexpected row visible")
AssertionError: Items in the first set but not the second:
'interim-2023-sg-01' : Unexpected row visible

======================================================================
FAIL: test_upcoming_view_filter_show_area (ietf.meeting.tests_js.InterimTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/ietf/meeting/tests_js.py", line 1139, in test_upcoming_view_filter_show_area
    self.do_upcoming_view_filter_test('?show=%s' % area.acronym, self.displayed_interims(groups=['mars', 'ames']))
  File "/workspace/ietf/meeting/tests_js.py", line 1048, in do_upcoming_view_filter_test
    self.assert_upcoming_meeting_visibility(visible_meetings)
  File "/workspace/ietf/meeting/tests_js.py", line 1003, in assert_upcoming_meeting_visibility
    self.assertEqual(unexpected, set(), "Unexpected row visible")
AssertionError: Items in the first set but not the second:
'interim-2023-sg-01' : Unexpected row visible

======================================================================
FAIL: test_upcoming_view_filter_show_group (ietf.meeting.tests_js.InterimTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/ietf/meeting/tests_js.py", line 1122, in test_upcoming_view_filter_show_group
    self.do_upcoming_view_filter_test('?show=')
  File "/workspace/ietf/meeting/tests_js.py", line 1048, in do_upcoming_view_filter_test
    self.assert_upcoming_meeting_visibility(visible_meetings)
  File "/workspace/ietf/meeting/tests_js.py", line 1003, in assert_upcoming_meeting_visibility
    self.assertEqual(unexpected, set(), "Unexpected row visible")
AssertionError: Items in the first set but not the second:
'interim-2023-sg-01' : Unexpected row visible
```

**Comment by jennifer-richards** [comment]
> @jennifer-richards I see these three failures still:
> 
> ```
> ======================================================================
> FAIL: test_upcoming_view_filter_hide_area (ietf.meeting.tests_js.InterimTests)
> ----------------------------------------------------------------------
[...]
> ======================================================================
> FAIL: test_upcoming_view_filter_show_area (ietf.meeting.tests_js.InterimTests)
> ----------------------------------------------------------------------
[...]
> ======================================================================
> FAIL: test_upcoming_view_filter_show_group (ietf.meeting.tests_js.InterimTests)
> ----------------------------------------------------------------------
> ```

Hmm, those are not failing here for me. Are you running tests on Windows?

**Comment by jennifer-richards** [comment]
For me (m2 mac, geckodriver 0.33.0 (a80e5fd61076 2023-04-02 18:31 +0000)):
```
dev ➜ /workspace $ ietf/manage.py test --settings=settings_test --skip-coverage ietf.meeting.tests_js.InterimTests
     Datatracker 11.0.0-dev test suite, 30 October 2023 12:05:35 PDT:
     Python 3.9.18 (main, Oct 12 2023, 02:21:43)  [GCC 10.2.1 20210110].
     Django 4.2.6, settings 'settings_test'
     Changing TEMPLATES[0]['OPTIONS']['string_if_invalid'] to '' during testing
     Changing INTERNAL_IPS to '[]' during testing.
     Running an SMTP test server on 127.0.0.1:2026 to catch outgoing email.
     Saving factory-boy random state to .factoryboy_random_state
     Validating all HTML generated during the tests
Found 12 test(s).
     Creating test database...
     Loading global test fixtures: names, ietf.utils.test_data.make_immutable_base_data, nomcom_templates, proceedings_templates
System check identified no issues (3 silenced).
............
----------------------------------------------------------------------
Ran 12 tests in 90.344s

OK
```
I previously ran the whole suite (without the `--skip-coverage`) without failure as well. Maybe it's a time-of-day or date-related thing? Or something to do with orbstack vs docker? (seems unlikely)

**Comment by larseggert** [comment]
Tests passed now...

**Comment by jennifer-richards** [comment]
Tests are still passing for me on my M2. Still have the bootstrapping problem for running the selenium tests on github CI, though.

**Comment by NGPixel** [comment]
geckodriver added to the base image.

**Comment by rjsparks** [comment]
What can we do to get insight into why geckodriver is crashing in the test container?

**Comment by NGPixel** [comment]
@rjsparks Use the tests debug script:

1. Clone the PR locally (`gh pr checkout 6541`)
2. cd to `dev/tests`
3. run `sh debug.sh`
4. after init, run:

```
./ietf/manage.py check
./ietf/manage.py migrate --fake-initial
./ietf/manage.py test -v2 --validate-html-harder --settings=settings_test
```

While this will run in the same environment setup as GHA, including the container being limited to 2 cores and 7GB of RAM, you'll be running in arm64, while GHA is using x64. So if you don't get the errors, a x64 environment would be needed to properly reproduce.

**Comment by larseggert** [comment]
What's in `geckodriver.log`?

**Comment by NGPixel** [comment]
@larseggert https://github.com/ietf-tools/datatracker/suites/18134236487/artifacts/1045634129

The recurring error being:
```
1699868894816	mozrunner::runner	INFO	Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/github/home/.cache/selenium/firefox/linux64/119.0.1/firefox" "--marionette" "--headless" "--remote-debugging-port" "51209" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/tmp/rust_mozprofileOPgBo4"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /github/home which is owned by uid 1001.)
```

**Comment by NGPixel** [comment]
Adding `HOME=/root` before running the tests appears to be working.

This is a long standing firefox specific bug that [they can't be bothered to fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1206441).

**Review by NGPixel — APPROVED** [review]

**Review by rjsparks — APPROVED** [review]

**Pull request merged**
