### PR TITLE
feat: Replace graphviz with d3

### PR DESCRIPTION
**Pull request by larseggert**
This eliminates the datatracker's dependency on graphviz, by using d3 to draw the document dependency graph.

### CODE REVIEW

**Comment by larseggert** [comment]
Need to figure out why @rjsparks sees different data in the graphs, and why Chrome doesn't like my SVG.

**Comment by larseggert** [comment]
@rjsparks maybe gives this another look? Made a bunch of changes.

**Comment by rjsparks** [comment]
I'm not getting any hover effects on the graph or the legend, even after a complete rebuild. I'll ask Nick to look.

**Comment by NGPixel** [comment]
I'm not getting any hover effects on the bubbles either.

**Review by rjsparks — APPROVED** [review]

**Comment by rjsparks** [comment]
This doesn't look right, but I think we're close enough to bring it in, and can address this (and some protonopia issues I have with the colors) later.

**Pull request merged**
