### PR TITLE
chore: Update HTML validator

### PR DESCRIPTION
**Pull request by larseggert**
And suppress new validator warnings

### CODE REVIEW

**Comment by NGPixel** [comment]
Duplicate of #5382? which is waiting on #5385 to be merged first.

**Comment by rjsparks** [comment]
I just merged #5385. #5382 has conflicts now.

**Comment by larseggert** [comment]
Some changes are redundant with #5382, but this one picks up more updates and also updates `vnu.jar`.

**Comment by larseggert** [comment]
@NGPixel once all the DePaul bits are in, let me know and I'll rebase this against the new main

**Comment by NGPixel** [comment]
#5382 merged.

**Review by rjsparks — APPROVED** [review]

**Pull request merged**
