### PR TITLE
fix: Fix layout issue in ballot modals on narrow screens

### LINKED ISSUE #4902: Wrapping issues in ballot modal on narrow screens
### Describe the issue

Screenshot 2022-12-15 at 18 02 42

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #4902

### CODE REVIEW

**Comment by larseggert** [comment]
Have been trying to reproduce this CI fail locally, but no luck: https://github.com/ietf-tools/datatracker/actions/runs/3713251155/jobs/6295685280#step:6:27

**Review by rjsparks — APPROVED** [review]

**Comment by rjsparks** [comment]
Looks like it was a transient - bet it was name related, but not enough output to say for sure. It passed when I just reran the failed jobs.

**Comment by larseggert** [comment]
@rjsparks here is a repeat where it failed, printing out `post_data` before and after modification. Don't see anything obvious wrong:
```
System check identified no issues (1 silenced).
{'basis': 'reorder the authors', 'author-TOTAL_FORMS': 4, 'author-INITIAL_FORMS': '3', 'author-MIN_NUM_FORMS': '0', 'author-MAX_NUM_FORMS': '1000', 'author-__prefix__-person': '', 'author-__prefix__-email': '', 'author-__prefix__-affiliation': '', 'author-__prefix__-country': '', 'author-__prefix__-ORDER': '', 'author-0-person': '32', 'author-0-email': 'brett.lambe_1@key.com', 'author-0-affiliation': 'Dixon-Johnson', 'author-0-country': 'Falkland Islands (Malvinas)', 'author-0-ORDER': '0', 'author-1-person': '33', 'author-1-email': 'monica.soto_2@zimmerman.net', 'author-1-affiliation': 'Reed-Gonzalez', 'author-1-country': 'Faroe Islands', 'author-1-ORDER': '1', 'author-2-person': '34', 'author-2-email': 'brenda.simmons_3@newton.com', 'author-2-affiliation': 'Snyder, Leon and Kelley', 'author-2-country': 'Chile', 'author-2-ORDER': '2'}
{'basis': 'reorder the authors', 'author-TOTAL_FORMS': 4, 'author-INITIAL_FORMS': '3', 'author-MIN_NUM_FORMS': '0', 'author-MAX_NUM_FORMS': '1000', 'author-__prefix__-person': '', 'author-__prefix__-email': '', 'author-__prefix__-affiliation': '', 'author-__prefix__-country': '', 'author-__prefix__-ORDER': '', 'author-0-person': '32', 'author-0-email': 'carolyn.hill_4@moore.com', 'author-0-affiliation': 'Dixon-Johnson', 'author-0-country': 'Falkland Islands (Malvinas)', 'author-0-ORDER': '0', 'author-1-person': '33', 'author-1-email': 'monica.soto_2@zimmerman.net', 'author-1-affiliation': 'University of Nowhere', 'author-1-country': 'Faroe Islands', 'author-1-ORDER': '1', 'author-2-person': '34', 'author-2-email': 'brenda.simmons_3@newton.com', 'author-2-affiliation': 'Snyder, Leon and Kelley', 'author-2-country': 'Chile', 'author-2-ORDER': '2'}
b''
F
======================================================================
FAIL: test_edit_authors_edit_fields (ietf.doc.tests.DocDraftTestCase.test_edit_authors_edit_fields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/ietf/doc/tests.py", line 1332, in test_edit_authors_edit_fields
    self.assertEqual(EditedAuthorsDocEvent.objects.count(), events_before + 3)
AssertionError: 2 != 3
```

**Comment by jennifer-richards** [comment]
Only two authors' data changed. Using the data you posted,
```
>>> {k: (before[k], after[k]) for k in before if before[k] != after[k]}
{'author-0-email': ('brett.lambe_1@key.com', 'carolyn.hill_4@moore.com'), 'author-1-affiliation': ('Reed-Gonzalez', 'University of Nowhere')}
```
I think the 3rd change is setting `author-2-country='Chile'` but it looks like it was already Chile.

**Comment by jennifer-richards** [comment]
(Working on a PR to fix that)

**Pull request merged**
