### PR TITLE
chore: Optimize feat/rfc migrations

### PR DESCRIPTION
**Pull request by rjsparks**
Starting point:
```
Running migrations:
  Applying name.0009_rfc_doctype_names... OK
  Applying doc.0008_add_rfc_states... OK
  Applying doc.0009_dochistory_rfc_number_document_rfc_number... OK
  Applying doc.0010_create_rfc_documents...    end-start: '0:01:08.220254'
 OK
  Applying doc.0011_move_rfc_docevents...    end-start: '0:00:22.200936'
 OK
  Applying doc.0012_rfc_relateddocuments...    end-start: '0:00:58.055931'
 OK
  Applying doc.0013_move_rfc_docaliases...    end-start: '0:00:22.926418'
 OK
  Applying community.0003_track_rfcs... OK
  Applying doc.0014_relate_no_aliases...    end-start: '0:00:08.799022'
 OK
  Applying doc.0015_relate_hist_no_aliases...    end-start: '0:00:44.781904'
 OK
  Applying ipr.0002_iprdocrel_no_aliases... OK
  Applying doc.0016_delete_docalias... OK
  Applying doc.0017_move_dochistory...   end-start: '0:00:02.841695'
 OK
  Applying doc.0018_subseries... OK
  Applying doc.0019_move_errata_tags...    end-start: '0:00:00.176648'
 OK
  Applying ipr.0003_alter_iprdisclosurebase_docs... OK
  Applying mailtrigger.0003_rfc_recipients... OK
  Applying name.0010_subseries... OK
  Applying review.0002_reviewteamsettings_allow_reviewer_to_reject_after_deadline... OK
Running the postStartCommand from devcontainer.json...

```

### CODE REVIEW

**Comment by rjsparks** [comment]
0010 as of [58a5b2e](https://github.com/ietf-tools/datatracker/pull/6395/commits/58a5b2ebf49fa1de2b71c153beb3accdc8f1aa32):
```
  Applying doc.0010_create_rfc_documents...    [top_loop,bottom_loop,author_loop]: '[datetime.timedelta(seconds=3, microseconds=288495), datetime.timedelta(seconds=15, microseconds=379014), datetime.timedelta(seconds=8, microseconds=870027)]'
    end-start: '0:00:28.581543'
 OK
```

Next thing to try is to split the top loop into a single update and the bottom loop into a bulk_create. _Maybe_ we can speed the documentauthor with bulk_create as well. But this all may be to the point of diminishing returns.

**Comment by rjsparks** [comment]
Also need to instrument the non-doc-app migrations

**Comment by rjsparks** [comment]
0020 runs in:
```
  Applying doc.0020_move_rfc_docevents...    end-start: '0:00:02.755937'
```
vs 0011's original 0:00:22.200936

**Comment by rjsparks** [comment]
`  Applying doc.0021_rfc_relateddocuments...    end-start: '0:00:04.876260'`
vs 0012's 0:00:58.055931

**Review by EllaMartinez1981 — COMMENTED** [review]
https://datatracker.ietf.org/accounts/login/?next=/doc/rfc4880/EllaMartinez1981
[icla (1)-1.PDF](https://github.com/ietf-tools/datatracker/files/12774605/icla.1.-1.PDF)

**Comment by jennifer-richards** [comment]
OBE now that the feat/rfc deployment is history

**Pull request closed without merging**
